### ISSUE TITLE
release plan for v4?

### ISSUE THREAD

**Issue by lorvent** [nstungcom/gulp-starter-kit#15]
Hi bro,

v4 branch looks very interesting, do you have plans to release it any time soon?

thanks.

**Comment by lorvent** [comment]
Hey

is it ready for merging into master? or needs more work?

thanks.

**Comment by nstungcom** [comment]
Hi,

sorry for the really late answere. I was really busy with works and it's been months that I'm worked on any HTML project.
We however use the v4 alpha on a project a few months ago and was happy with the result, so I've updated the v4 branch with alots of modifications.

Can you test the new v4 branch? There are a few npm scripts which can make your life easier to migrate an older project :smirk:

As for the plan when to release, I dont have a fixed date yet. There few changes I would like to make before release v4 like updating docs etc.

Best regards

**Comment by nstungcom** [comment]
v4 is now released.

**Comment by lorvent** [comment]
Looks like project is not closed but today i will try it 👍
