### ISSUE TITLE
using dart-sass instead of node-sass

### ISSUE THREAD

**Issue by lorvent** [nstungcom/gulp-starter-kit#6]
dart-sass seems to be giving less problems compared to node-sass

**Comment by nstungcom** [comment]
Hi,

I will try it out if there is time.

**Comment by nstungcom** [comment]
Hi, for now we will stick with `node-sass` see: 

https://stackoverflow.com/questions/56150402/vue-cli-css-pre-processor-option-dart-sass-vs-node-sass

**Comment by lorvent** [comment]
same SO article now suggests using dart over node-sass so i hope you may consider it.
