### ISSUE TITLE
how to convert multiple sass files to css

### ISSUE THREAD

**Issue by lorvent** [nstungcom/gulp-starter-kit#7]
Hello,

can you tell me how to convert multile sass files to css in proper way?

i have many sass files which i want to convert into css seperately (not combining them)

earlier, i have used laravel-mix, which has option like `gulp.sass(src,dest);`, do we have something like that here?

thanks.

**Comment by nstungcom** [comment]
Hi,

you can edit the **[gulpfile.babel.js](https://github.com/nstungcom/gulp-starter-kit/blob/master/gulpfile.babel.js#L51)** and **[default.html](https://github.com/nstungcom/gulp-starter-kit/blob/master/src/pages/layouts/default.html#L8)** to achieve that in v2.0.0.
