### ISSUE TITLE
combining css files

### ISSUE THREAD

**Issue by lorvent** [nstungcom/gulp-starter-kit#8]
Hello,

instead of loading multiple css (or js) files into layout file, i just want to combine/concat them into something like app.css (or app.js)

is it possible with gulp-starter-kit or we need to modify it?

thanks.

**Comment by nstungcom** [comment]
Hi,

there is no task which concate multiple css or js files, you should modify it as your needs. When auto concate css or js files the order might be wrong and could breaks your code so a task to manually concate them should be created as your needs.
